name: General GHA Testing
on:
  workflow_dispatch:
    inputs:
      skip_apply:
        type: boolean
        description: Do I just plan
        required: false
        default: true
  push:
    branches: ["*"]

jobs:
  tf-plan-apply:
    uses: ./.github/workflows/tf.plan-apply.yml
    with:
      terraform_path: app1/envs/dev
      terraform_plan_args: -var valid=super
      skip_apply: ${{ inputs.skip_apply }}
    permissions:
      issues: write
