name: General GHA Testing
on:
  workflow_dispatch:
    inputs:
      plan_only:
        type: boolean
        description: Do I just plan
        required: false
        default: true
  # push:
  #   branches: ["*"]

jobs:
  tf-plan-apply:
    uses: ./.github/workflows/tf.plan-apply.yml
    with:
      terraform_path: app1/envs/test
      plan_only: ${{ inputs.plan_only }}
    permissions:
      issues: write
