name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v40.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_ONBOARDING: "false"
          RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
          RENOVATE_AUTODISCOVER: "false"
          RENOVATE_REPOSITORIES: tylottr-lab/tf-gha-pipelining
          LOG_LEVEL: debug