name: app1

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/terraform.config.app1.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf
      - app1/envs/test/*.tf
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/terraform.config.app1.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf
      - app1/envs/test/*.tf

jobs:
  tf-plan-apply:
    strategy:
      matrix:
        configs:
          - environment: dev
            skip_apply: false
            terraform_plan_args: -var valid=dev
          - environment: test
            skip_apply: true
            terraform_plan_args: -var valid=test
    uses: ./.github/workflows/tf.plan-apply.yml
    with:
      terraform_path: app1/envs/${{ matrix.configs.environment }}
      terraform_plan_args: ${{ matrix.configs.terraform_plan_args }}
      skip_apply: ${{ matrix.configs.skip_apply }}
      environment: ${{ matrix.configs.environment }}
