name: app1

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/terraform.config.app1.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf
      - app1/envs/test/*.tf
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/terraform.config.app1.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf
      - app1/envs/test/*.tf

jobs:
  # setup-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: setup-env
  #       run: |
  #         echo "TF_VAR_valid=set-through-prior-job" >> "$GITHUB_ENV"
  tf-plan-apply:
    permissions:
      issues: write
    strategy:
      matrix:
        configs:
          - environment: dev
            skip_apply: false
            # terraform_plan_args: -var valid=dev
          - environment: test
            skip_apply: false
            # terraform_plan_args: -var valid=test
    uses: ./.github/workflows/tf.plan-apply.yml
    with:
      # renovate: datasource=terraform
      terraform_version: "1.8.5"
      terraform_path: app1/envs/${{ matrix.configs.environment }}
      terraform_plan_args: ${{ matrix.configs.terraform_plan_args }}
      skip_apply: ${{ matrix.configs.skip_apply }}
      environment: ${{ matrix.configs.environment }}
      # approvers: tylottr
