######################################################
# Terraform Test Workflow
#
# Performs a simple test to ensure that Terraform is:
# - Formatted correctly
# - (optional) Validates
# - (optional) run tflint
# - (optional) run tfsec
#
# ###OMITTED###
# jobs:
#   terraform_job:
#     uses: ./.github/workflows/tf.test.yml # or: GITHUB_OWNER/REPO_NAME/.github/workflows/tf.test.yml@main
#     with:
#       terraform_path: path/to/module
#     permissions:
#       contents: read
#       checks: write
#       pull-requests: write
#       security-events: write
# ###OMITTED###
######################################################

name: terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: Terraform version to use.
        required: false
        default: latest
      terraform_path:
        type: string
        description: Path to the location of your Terraform configuration or module.
        required: false
        default: "."
      environment:
        type: string
        description: Environment to use for apply operations
        required: false
        default: terraform
      enable_fmt:
        type: boolean
        description: Run terraform fmt
        required: false
        default: true
      enable_validate:
        type: boolean
        description: Run terraform validate
        required: false
        default: true
      enable_tflint:
        type: boolean
        description: Run tflint
        required: false
        default: true
      enable_tfsec:
        type: boolean
        description: Run tfsec
        required: false
        default: true
      reviewdog_pr_reporter:
        type: string
        description: The reporter to use with Reviewdog and PR.
        required: false
        default: github-pr-check
      enable_trivy:
        type: boolean
        description: Run trivy
        required: false
        default: true
      enable_test:
        type: boolean
        description: Run terraform test
        required: false
        default: false
      enable_plan:
        type: boolean
        description: Run terraform plan
        required: false
        default: false
      enable_apply:
        type: boolean
        description: Run terraform apply
        required: false
        default: false

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:
  fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_path }}
    permissions:
      contents: read
    if: inputs.enable_fmt
    steps:
      - uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: terraform fmt
        run: terraform fmt -check
        continue-on-error: true

  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_path }}
    permissions:
      contents: read
    if: inputs.enable_validate
    steps:
      - uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: terraform init
        run: terraform init
        env:
          TF_CLI_ARGS_init: -backend=false
      - name: terraform validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    if: inputs.enable_tflint
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          filter_mode: nofilter
          reporter: github-check
          fail_on_error: false
          tflint_init: true
          working_directory: ${{ inputs.terraform_path }}
        if: github.event_name != 'pull_request'
      - name: tflint-pr
        uses: reviewdog/action-tflint@v1
        with:
          filter_mode: nofilter
          reporter: ${{ inputs.reviewdog_pr_reporter }}
          fail_on_error: false
          tflint_init: true
          working_directory: ${{ inputs.terraform_path }}
        if: github.event_name == 'pull_request'

  tfsec:
    runs-on: ubuntu-latest
    if: inputs.enable_tfsec
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: tfsec
        uses: reviewdog/action-tfsec@v1
        with:
          filter_mode: nofilter
          reporter: github-check
          fail_on_error: false
          working_directory: ${{ inputs.terraform_path }}
        if: github.event_name != 'pull_request'
      - name: tfsec-pr
        uses: reviewdog/action-tfsec@v1
        with:
          filter_mode: nofilter
          reporter: ${{ inputs.reviewdog_pr_reporter }}
          fail_on_error: true
          working_directory: ${{ inputs.terraform_path }}
        if: github.event_name == 'pull_request'
  
  trivy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_path }}
    if: inputs.enable_trivy
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: trivy
        uses: aquasecurity/trivy-action@0.21.0
        with:
          scan-type: config
          exit-code: 0
          hide-progress: true
          ignore-unfixed: true
          format: sarif
          output: trivy.sarif
      - name: upload trivy scan
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_path }}
    needs: [fmt, validate, tflint, tfsec, trivy]
    permissions:
      contents: read
    if: inputs.enable_test
    steps:
      - uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: terraform init
        run: terraform init
      - name: terraform test
        run: terraform test

  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_path }}
    needs: [test]
    permissions:
      contents: read
    if: inputs.enable_plan
    steps:
      - uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan -out tf.plan
      - name: upload plan
        uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: plan
          path: "**/tf.plan"
          if-no-files-found: error
          overwrite: true

  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.terraform_path }}
    needs: [plan]
    permissions:
      contents: read
    environment:
      name: ${{ inputs.apply_environment }}
    if: inputs.enable_apply
    steps:
      - uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: terraform init
        run: terraform init
      - name: download plan
        uses: actions/download-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: plan
      - name: terraform apply
        run: terraform apply tf.plan
