name: app1-dev

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.config.app1.dev.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.config.app1.dev.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf

jobs:
  tf-code-quality:
    uses: ./.github/workflows/tf.code-quality.yml
    with:
      terraform_path: app1/envs/dev
      enable_test: false
      enable_tflint: true
      enable_trivy: true
      enable_checkov: true
    permissions:
      contents: read
      checks: write
      pull-requests: write
      security-events: write
  tf-plan-apply:
    uses: ./.github/workflows/tf.plan-apply.yml
    with:
      # renovate: datasource=github-releases depName=hashicorp/terraform
      terraform_version: 1.7.3
      terraform_path: app1/envs/dev
      # continue_on_fmt_error: true
      terraform_plan_args: -var valid=super
      # plan_only: true
      environment: terraform
    permissions:
      contents: read
      issues: write
    needs: [tf-code-quality]
