name: app1-dev

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.env.dev.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.env.dev.yml
      - app1/modules/app1/*.tf
      - app1/envs/dev/*.tf

jobs:
  code-quality:
    uses: ./.github/workflows/tf.code-quality.yml
    with:
      terraform_path: app1/envs/dev
      enable_test: false
      enable_tflint: false
      enable_trivy: false
      enable_checkov: false
    permissions:
      contents: read
      checks: write
      pull-requests: write
      security-events: write
  plan-apply:
    uses: ./.github/workflows/tf.plan-apply.yml
    with:
      terraform_path: app1/envs/dev
      terraform_plan_args: -var valid=super
      # skip_apply: true
      environment: terraform
    permissions:
      contents: read
    needs: [code-quality]
